---
matrix:
  include:
  - name: "Angular Client Unit Tests"
    sudo: required
    addons:
      chrome: stable
    language: node_js
    node_js:
      - "10"
    install:
      - npm install -g @angular/cli
      - cd frontend/
      - npm ci
    script:
      - ng build --prod --configuration=prod
      - ng test --watch=false
  - name: "Java Spring Server Unit Tests"
    language: java
    jdk: oraclejdk8
    install:
      - cd backend/
      - ./gradlew assemble
    script:
      - ./gradlew test
  - name: "E2E Tests"
    language: java
    jdk: oraclejdk8
    env:
      - NODE_VERSION="10.9.0"
    before_install:
      - chmod +x ci-e2e-tests.sh
    script:
      - bash ci-e2e-tests.sh
