---
matrix:
  include:
  - name: "Angular Client Unit Tests"
    sudo: required
    addons:
      chrome: stable
    language: node_js
    node_js:
      - "10"
    install:
      - npm install -g @angular/cli
      - cd frontend/
      - npm ci
    script:
      - ng build --prod --configuration=prod
      - ng test --watch=false
